apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - image: lekhaselliah/netflix-usecase:tagname
        name: netflix
        ports:
        - containerPort: 80
