name: Netflix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ubuntu update
      run: |
         sudo apt-get autoclean -y
         sudo apt-get update
         sudo apt-get upgrade -y
         sudo rm -rf node_modules
         yarn cache clean
         yarn
    - name: Build & Push Image
      run: | 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lekhaselliah" --password-stdin
        docker image build -t lekhaselliah/netflix-usecase:v2 .
        docker push lekhaselliah/netflix-usecase:v2
