name: Netflix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ubuntu update
      run: |
         sudo apt-get autoclean -y
         sudo apt-get update
         sudo apt-get upgrade -y
         sudo rm -rf node_modules
         sudo apt install yarn
         yarn --version
    - name: Build & Push Image
      run: | 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lekhaselliah" --password-stdin
        docker build -t netflix-username . 
        docker tag netflix-username lekhaselliah/netflix-username:tagname
        docker push lekhaselliah/netflix-username:tagname
