name: Netflix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: | 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "lekhaselliah" --password-stdin
        docker image build -t lekhaselliah/netflix-usecase:v2 .
        docker push lekhaselliah/netflix-usecase:v2
